### ISSUE TITLE
 Confusion matrix 

### ISSUE THREAD

**Issue by vis58** [Altimis/Confusion-matrix-for-Matterport-implementation-of-Mask-R-CNN#3]
Hello @Altimis  , I tried to use your code to generate confusion matrix , but I got the following error. 
I have NUM_CLASSES = 1 + 4 (4 class and 1 background). please help me in resoving this issue .

<img width="857" alt="Capture" src="https://user-images.githubusercontent.com/59176298/100521293-1b138500-3179-11eb-8a0b-dab131584015.PNG">

**Comment by Altimis** [comment]
Hello @vis58, It appears that your y_test doesnt cover all the possible labels (I think). Because in my code, I tried to get the num_classes from num_classes = len(np.unique(y_test)). Can you go to the utils.py and set the num_classes to the actual num_classes that you have (5 in yout case) please ? let me know if you solved this problem so that I can update the code.

**Comment by vis58** [comment]
Hello @Altimis  , I have changed num_classes 

<img width="326" alt="Capture1" src="https://user-images.githubusercontent.com/59176298/100521760-f371ec00-317b-11eb-846b-2dc37f567715.PNG">

Should I need to change in len(y_test) ?

<img width="558" alt="Capture" src="https://user-images.githubusercontent.com/59176298/100521773-0d133380-317c-11eb-8fe8-3bc8f06d7e0f.PNG">

**Comment by Altimis** [comment]
No len(y_test) is the number of samples of yout test data. The probem here is at the level of the num_classes.

**Comment by vis58** [comment]
ok thanks, I will let you know whether it works or not.

**Comment by vis58** [comment]
@Altimis, it worked, thankyou for your help.

**Comment by Altimis** [comment]
@vis58 Happy to help. Thank you for detecting this issue. I will update the code to extract the num_class in a more efficient way.
