### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by vishnuvardhan58** [Altimis/Confusion-matrix-for-Matterport-implementation-of-Mask-R-CNN#4]
Hello @Altimis  , I am getting a strange error when trying to print confusion matrix.Please help me in resolving this,

![Capture](https://user-images.githubusercontent.com/9161539/100767870-a175d400-33d0-11eb-8faa-3a65e1fd9105.PNG)

**Comment by Altimis** [comment]
Hello @vishnuvardhan58 , could you please show me the whole error message. Did you generate the gt_tot and pred_tot lists of ground-truth and predictons ?

**Comment by vishnuvardhan58** [comment]
Hello @Altimis  ,here is the whole error message

![Capture](https://user-images.githubusercontent.com/9161539/100768927-d0407a00-33d1-11eb-990b-6f343bcc5b0b.PNG)

![Capture2](https://user-images.githubusercontent.com/9161539/100768981-de8e9600-33d1-11eb-8e1c-5a88df7abd15.PNG)

**Comment by vishnuvardhan58** [comment]
yes , I have generated  gt_tot and pred_tot lists of ground-truth and predictons .

**Comment by Altimis** [comment]
Hi again @vishnuvardhan58 , I think that I spotted where is the problem. The porblem is in the line 
`columns = range(1, len(np.unique(y_test))+1)`
Either you need to remove the "+1" or set `len(np.unique(y_test))` to the number of your classes + 1 (background). If neither f these work, please let me know.

**Comment by Altimis** [comment]
I would like to take a look at your gt_tot and pred_tot

**Comment by vishnuvardhan58** [comment]
Hello @Altimis  , I am still getting the same error after making the above changes , 

Please find the gt_tot and pred_tot values , I have 3 images in my test_set


![Capture](https://user-images.githubusercontent.com/9161539/100772726-59f24680-33d6-11eb-8646-db09cbc09c4b.PNG)

**Comment by Altimis** [comment]
Ah okey I get it. In fact, the `columns = range(1, len(np.unique(y_test))+1)` means that there is (1,5) since `len(np.unique(gt_tot)) = 4` in your case. But your pred_tot vector doesn't contain background class (0) so it's len is equal to 3 and not 4 like gt_tot. 
The problem is exacty in `df_cm = DataFrame(confm, index=columns, columns=columns)` since I've set `index = columns = range(1, len(np.unique(y_test))+1)` since confusion matrix should be square. In fact i didnt include in my code the case where the model doesn't detect background intead of an object (you used only 3 images, if you used more for testing I'm sure this probleme wont occure.

**Comment by Altimis** [comment]
I will try to solve this problem by including the case where the model doesn't miss ^^. For now, you can test your model on more data and it will probably work

**Comment by vishnuvardhan58** [comment]
I will try with more data @Altimis  , and I will let you know.

**Comment by vishnuvardhan58** [comment]
Hello @Altimis ,it is working if I have more images. Thankyou.

**Comment by Altimis** [comment]
Great! Happy to help. I will fixe this issue as soon as possible, thank you .

**Comment by Altimis** [comment]
Hi @vishnuvardhan58, I think that I fixed the issue. Can you please check if it works for only 2 images ?
